# Generated by Django 5.2.15 on 2026-08-23 00:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent_infra", "0002_outbox_idempotency_attention"),
        ("agent_infra", "0002_serviceidentity"),
    ]

    operations = []
