# Generated by Django 5.2.15 on 2026-08-23 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent_infra", "0003_merge_20260823_0027"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="agentinfraattentionitem",
            new_name="agent_infra_workspa_7675d0_idx",
            old_name="agent_infra_workspa_5d0f8f_idx",
        ),
        migrations.RenameIndex(
            model_name="agentinfraattentionitem",
            new_name="agent_infra_entity__79e1c5_idx",
            old_name="agent_infra_entity__f8f8f8_idx",
        ),
        migrations.RenameIndex(
            model_name="agentinfraoutbox",
            new_name="agent_infra_status_9f6574_idx",
            old_name="agent_infra_status_8f0d0d_idx",
        ),
        migrations.RenameIndex(
            model_name="idempotencyrecord",
            new_name="agent_infra_expires_fdb1a7_idx",
            old_name="agent_infra_expires_0d8f8a_idx",
        ),
    ]
