# Generated by Django 5.2.15 on 2026-08-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_infra", "0005_idempotencyrecord_fingerprint_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="idempotencyrecord",
            name="state",
            field=models.CharField(
                choices=[("in_progress", "In Progress"), ("completed", "Completed")],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="idempotencyrecord",
            name="response_body",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="idempotencyrecord",
            name="response_status",
            field=models.IntegerField(default=0),
        ),
    ]
