# Generated by Django 5.2.15 on 2026-08-23 01:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_infra", "0006_idempotency_state_field"),
        ("db", "0123_project_is_agent_infra_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeSource",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("plane", "Plane"),
                            ("repository", "Repository"),
                            ("ci", "CI"),
                            ("incident", "Incident"),
                            ("external", "External"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "authority_type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("design", "Design"),
                            ("architecture", "Architecture"),
                            ("qa", "QA"),
                            ("security", "Security"),
                            ("platform", "Platform"),
                            ("release", "Release"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sensitivity",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("restricted", "Restricted"),
                        ],
                        default="internal",
                        max_length=50,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("retention_days", models.PositiveIntegerField(default=365)),
                ("is_retired", models.BooleanField(default=False)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_knowledge_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_sources",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_sources",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Source",
                "verbose_name_plural": "Knowledge Sources",
                "db_table": "agent_infra_knowledge_sources",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="KnowledgeVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("content_hash", models.CharField(max_length=64)),
                ("diff_summary", models.TextField(blank=True)),
                ("is_agent_generated", models.BooleanField(default=False)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_versions",
                        to="db.project",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_knowledge_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="agent_infra.knowledgesource",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_versions",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Version",
                "verbose_name_plural": "Knowledge Versions",
                "db_table": "agent_infra_knowledge_versions",
                "ordering": ("-version_number",),
            },
        ),
        migrations.CreateModel(
            name="ContextManifest",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("bound_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_manifests",
                        to="db.project",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_manifests",
                        to="agent_infra.agentrun",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_manifests",
                        to="db.workspace",
                    ),
                ),
                (
                    "knowledge_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manifest_entries",
                        to="agent_infra.knowledgeversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Context Manifest",
                "verbose_name_plural": "Context Manifests",
                "db_table": "agent_infra_context_manifests",
                "ordering": ("-bound_at",),
            },
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["workspace", "project"], name="agent_infra_workspa_fa727b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["source_type"], name="agent_infra_source__88763c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgesource",
            index=models.Index(
                fields=["is_retired"], name="agent_infra_is_reti_8c6e66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgeversion",
            index=models.Index(fields=["status"], name="agent_infra_status_595643_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgeversion",
            index=models.Index(
                fields=["source", "status"], name="agent_infra_source__428433_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgeversion",
            unique_together={("source", "version_number")},
        ),
        migrations.AlterUniqueTogether(
            name="contextmanifest",
            unique_together={("run", "knowledge_version")},
        ),
    ]
