# Generated by Django 5.2.15 on 2026-08-23 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_infra", "0007_knowledge_source_version_manifest"),
        ("db", "0123_project_is_agent_infra_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogRevision",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("skill", "Skill"),
                            ("model", "Model"),
                            ("environment", "Environment"),
                            ("integration", "Integration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_ref", models.CharField(max_length=255)),
                ("revision_number", models.PositiveIntegerField()),
                ("content_hash", models.CharField(max_length=64)),
                ("content_snapshot", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("diff_summary", models.JSONField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "previous_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_revisions",
                        to="agent_infra.catalogrevision",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_revisions",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_revisions",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "agent_infra_catalog_revision",
                "ordering": ["-revision_number"],
                "unique_together": {
                    (
                        "workspace",
                        "project",
                        "entity_type",
                        "entity_ref",
                        "revision_number",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="CompatibilityRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("skill", "Skill"),
                            ("model", "Model"),
                            ("environment", "Environment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_ref", models.CharField(max_length=255)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("skill", "Skill"),
                            ("model", "Model"),
                            ("environment", "Environment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_ref", models.CharField(max_length=255)),
                ("compatible", models.BooleanField()),
                ("reason", models.TextField(blank=True, default="")),
                ("last_checked_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility_records",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility_records",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "agent_infra_compatibility_record",
                "unique_together": {
                    (
                        "workspace",
                        "project",
                        "source_type",
                        "source_ref",
                        "target_type",
                        "target_ref",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="EnvironmentRevision",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("environment_ref", models.CharField(max_length=255)),
                ("revision_number", models.PositiveIntegerField()),
                ("content_hash", models.CharField(max_length=64)),
                ("snapshot", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "drift_status",
                    models.CharField(
                        choices=[
                            ("in_sync", "In Sync"),
                            ("drifted", "Drifted"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("drift_detail", models.JSONField(blank=True, null=True)),
                ("last_drift_check_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environment_revisions",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environment_revisions",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "agent_infra_environment_revision",
                "ordering": ["-revision_number"],
                "unique_together": {
                    ("workspace", "project", "environment_ref", "revision_number")
                },
            },
        ),
        migrations.CreateModel(
            name="IntegrationRegistration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("integration_ref", models.CharField(max_length=255)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("mcp", "MCP"),
                            ("a2a", "A2A"),
                            ("git_ci", "Git/CI"),
                            ("deployment", "Deployment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "server_identity",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("degraded", "Degraded"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unreachable", "Unreachable"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("last_health_check_at", models.DateTimeField(blank=True, null=True)),
                ("granted_agents", models.JSONField(default=list)),
                ("granted_scopes", models.JSONField(default=list)),
                (
                    "approval_class",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("manual", "Manual"),
                            ("restricted", "Restricted"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                (
                    "failure_rate_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_registrations",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_registrations",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "agent_infra_integration_registration",
                "unique_together": {("workspace", "project", "integration_ref")},
            },
        ),
        migrations.CreateModel(
            name="ModelRoutingConfig",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("model_ref", models.CharField(max_length=255)),
                ("routing_priority", models.IntegerField(default=100)),
                ("shadow_mode", models.BooleanField(default=False)),
                (
                    "budget_limit_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "budget_used_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("eligible_risk_classes", models.JSONField(default=list)),
                ("eligible_assignment_types", models.JSONField(default=list)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_routing_configs",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_routing_configs",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "agent_infra_model_routing_config",
                "ordering": ["routing_priority"],
                "unique_together": {("workspace", "project", "model_ref")},
            },
        ),
        migrations.CreateModel(
            name="ProjectAgentEnablement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("agent_ref", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "max_autonomy_level",
                    models.CharField(
                        choices=[
                            ("supervised", "Supervised"),
                            ("semi_autonomous", "Semi-Autonomous"),
                            ("autonomous", "Autonomous"),
                        ],
                        default="supervised",
                        max_length=20,
                    ),
                ),
                ("allowed_assignment_types", models.JSONField(default=list)),
                ("delegation_permissions", models.JSONField(default=list)),
                ("enabled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "enabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_enablements",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_enablements",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "agent_infra_project_agent_enablement",
                "indexes": [
                    models.Index(
                        fields=["workspace", "project"],
                        name="agent_infra_workspa_50ad8d_idx",
                    )
                ],
                "unique_together": {("workspace", "project", "agent_ref")},
            },
        ),
    ]
