# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("agent_infra", "0011_agentrun_progression_fields"),
        ("db", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizationPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("description", models.TextField()),
                ("scope", models.CharField(choices=[("workspace", "Workspace"), ("project", "Project")], default="project", max_length=20)),
                ("priority", models.IntegerField(default=100)),
                ("effect", models.CharField(choices=[("allow", "Allow"), ("deny", "Deny"), ("require_approval", "Require Approval")], max_length=20)),
                ("subjects", models.JSONField(help_text="List of subject definitions")),
                ("resources", models.JSONField(help_text="List of resource definitions")),
                ("actions", models.JSONField(help_text="List of action definitions")),
                ("conditions", models.JSONField(blank=True, help_text="Additional matching conditions", null=True)),
                ("separation_of_duty", models.JSONField(blank=True, help_text="Separation-of-duty constraint rules", null=True)),
                ("autonomy_classification", models.CharField(blank=True, choices=[("unattended", "Unattended"), ("supervised", "Supervised"), ("attended", "Attended")], max_length=20, null=True)),
                ("emergency", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("pending_approval", "Pending Approval"), ("active", "Active"), ("deprecated", "Deprecated"), ("revoked", "Revoked")], default="draft", max_length=20)),
                ("content_hash", models.CharField(max_length=64)),
                ("revision_number", models.PositiveIntegerField(default=1)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("owner", models.CharField(blank=True, max_length=255, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True, null=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="authorization_policies", to="db.workspace")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="authorization_policies", to="db.project")),
                ("previous_revision", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="next_revisions", to="agent_infra.authorizationpolicy")),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("revoked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "agent_infra_authorization_policies",
                "ordering": ["priority", "-revision_number"],
                "unique_together": {("workspace", "name", "revision_number")},
            },
        ),
        migrations.CreateModel(
            name="PolicyDecision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("subject_type", models.CharField(max_length=50)),
                ("subject_ref", models.CharField(max_length=255)),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_ref", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=100)),
                ("outcome", models.CharField(choices=[("allow", "Allow"), ("deny", "Deny"), ("require_approval", "Require Approval")], max_length=20)),
                ("matching_policies", models.JSONField(help_text="List of policy IDs that matched, in evaluation order")),
                ("evaluation_context", models.JSONField(blank=True, help_text="Snapshot of context evaluated", null=True)),
                ("reason", models.TextField(help_text="Human-readable explanation of why this outcome was reached")),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                ("correlation_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="policy_decisions", to="db.workspace")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="policy_decisions", to="db.project")),
                ("deciding_policy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decisions", to="agent_infra.authorizationpolicy")),
                ("run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="policy_decisions", to="agent_infra.agentrun")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "agent_infra_policy_decisions",
                "ordering": ["-evaluated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="policydecision",
            index=models.Index(fields=["workspace", "subject_type", "subject_ref"], name="agent_infra_pd_subj_idx"),
        ),
        migrations.AddIndex(
            model_name="policydecision",
            index=models.Index(fields=["workspace", "resource_type", "action"], name="agent_infra_pd_res_act_idx"),
        ),
        migrations.CreateModel(
            name="ActionApproval",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("subject_type", models.CharField(max_length=50)),
                ("subject_ref", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=50)),
                ("target_ref", models.CharField(max_length=255)),
                ("target_digest", models.CharField(blank=True, max_length=128, null=True)),
                ("target_diff", models.JSONField(blank=True, null=True)),
                ("credential_scope", models.JSONField(blank=True, null=True)),
                ("budget_impact", models.JSONField(blank=True, null=True)),
                ("risk_level", models.CharField(default="medium", max_length=20)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("expired", "Expired"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("correlation_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="action_approvals", to="db.workspace")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="action_approvals", to="db.project")),
                ("policy_decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="approval_requests", to="agent_infra.policydecision")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_approvals", to=settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_approvals", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "agent_infra_action_approvals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="actionapproval",
            index=models.Index(fields=["workspace", "status"], name="agent_infra_aa_ws_status_idx"),
        ),
        migrations.AddIndex(
            model_name="actionapproval",
            index=models.Index(fields=["workspace", "project", "status"], name="agent_infra_aa_proj_status_idx"),
        ),
        migrations.CreateModel(
            name="SeparationOfDutyConstraint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("conflicting_actions", models.JSONField(help_text="List of action names that cannot be performed by the same actor")),
                ("scope", models.CharField(choices=[("run", "Run"), ("assignment", "Assignment"), ("project", "Project"), ("workspace", "Workspace")], default="run", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sod_constraints", to="db.workspace")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sod_constraints", to="db.project")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sod_constraints", to="agent_infra.authorizationpolicy")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "agent_infra_sod_constraints",
                "ordering": ["name"],
                "unique_together": {("workspace", "policy", "name")},
            },
        ),
        migrations.CreateModel(
            name="EmergencyDeny",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(help_text="Why this emergency deny was activated")),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("scope_filter", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivation_reason", models.TextField(blank=True, null=True)),
                ("incident_reference", models.CharField(blank=True, max_length=255, null=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="emergency_denies", to="db.workspace")),
                ("policy", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="emergency_activations", to="agent_infra.authorizationpolicy")),
                ("activated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="emergency_activations", to=settings.AUTH_USER_MODEL)),
                ("deactivated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="emergency_deactivations", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "agent_infra_emergency_denies",
                "ordering": ["-activated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emergencydeny",
            index=models.Index(fields=["workspace", "is_active"], name="agent_infra_ed_ws_active_idx"),
        ),
    ]
